### ISSUE TITLE
MQTT TLS Management

### ISSUE THREAD

**Issue by alexmc1510** [barnstee/UA-CloudPublisher#6]
Hello,

First of all, congratulations on your code. It is a really nice idea.
I am testing it deeply and I would like to know in a more deeper detail how to manage the TLS on MQTT side with the certificates. In my case I have a MQTT broker with its client certificate but I don't know how to install or deploy the CA on client side...
Can you explain how it is managed internally and how can I use it?

Regards

**Comment by barnstee** [comment]
Hi @alexmc1510. I'm glad you like it! MQTT broker auth with a broker-supplied cert is currently not implemented. :-) Only client-provided cert auth and username and password auth are. For the client-provided cert auth, I simply use the OPC UA client cert and this is why I display the OPC UA client cert thumbprint in the config page, so you can provide this info to your broker. If that doesn't work for you, it would be relatively trivial to add a file open dialog and upload a custom client cert to UA Cloud Publisher and add an if to the MqttClientCertificatesProvider:GetCertificates() method to load that cert instead of the OPC UA client cert. Leave it with me for a couple of hours... ;-)

**Comment by alexmc1510** [comment]
Hello,

I will fork your repo and work on it. I will come back to you with the
result.
Anyway...in order to undertand how to include TLS with you current code, if
I click on MQTT TLS, I think you generate and use a self signed certificate
but...how to include it for example in mosquitto?

Thanks in advance,

**Comment by barnstee** [comment]
I beat you to it: https://github.com/barnstee/UA-CloudPublisher/commit/4562fd57086334a9df955c1d772ebb147809993e
:-)

**Comment by barnstee** [comment]
To use it, make sure you check the Use custom certificate to authenticate with the Broker:
![image](https://github.com/barnstee/UA-CloudPublisher/assets/8157818/e525da94-cf5d-4105-8e63-2067066c4783)

**Comment by alexmc1510** [comment]
C'mon barnstee let me strees my brain just a bit...

By the way, have you ever tried to store the data and metadata arriving to
the broker in databases like influxdb for timeseries and another db for
metadata? I am trying to do it.

**Comment by barnstee** [comment]
:-)

Yes, there is a Telegraf connector for Azure Event Hubs and it can be used to send the data to InfluxDB and then use the built-in Grafana dashboard functionality. However, I found the free version of Azure Data Explorer to be easier to use for creating dashboards: https://dataexplorer.azure.com/freecluster
